Added data validation for registration form. Closed #5
TopAcademy2022/messenger-client pull request #16
Opened 2024-08-16 18:16 UTC by London3149-train

Added data validation for registration form. Closed #5

2024-08-16 18:21 UTC, SugarSalt9 submitted a review, later dismissed

2024-08-19 17:53 UTC, SugarSalt9 approved these changes, later dismissed

2024-08-19 17:53 UTC, Andrey31ts submitted a review, later dismissed

2024-08-19 18:00 UTC, xs887z approved these changes, later dismissed

2024-08-19 18:03 UTC, TopAcademy2022 requested changes

2024-08-19 18:03 UTC, TopAcademy2022 commented on messenger-client/Services/Interfeces/IBlockInjections.cs
> +        public bool CheckForProhibitedSymbol(string str);
Remove "For" from method name. Rename method parameter.

2024-08-19 18:03 UTC, TopAcademy2022 commented on messenger-client/Pages/Registration.cshtml.cs
> +		public void OnGet(bool regRes)
Delete method parameter and clear context. Or remove method.

2024-08-19 18:03 UTC, TopAcademy2022 commented on messenger-client/Pages/Registration.cshtml.cs
> +		private IBlockInjections blockInjections = new BlockInjections();
Add space.

2024-08-19 18:03 UTC, TopAcademy2022 commented on messenger-client/Pages/Registration.cshtml.cs
> +			if (login != String.Empty && password != String.Empty && email != String.Empty)
Replace this. Using String.IsNullOrEmpty() method.

2024-08-19 18:03 UTC, TopAcademy2022 commented on messenger-client/Services/BlockInjections.cs
> +        private char[] _ListProhibitedSymbol;
Add space.

2024-08-19 18:03 UTC, TopAcademy2022 commented on messenger-client/Services/BlockInjections.cs
> +using static System.Net.Mime.MediaTypeNames;
What the library?

2024-08-19 18:03 UTC, TopAcademy2022 commented on messenger-client/Services/BlockInjections.cs
> +        public bool CheckForProhibitedSymbol(string verifiedText)
Add space.

2024-08-19 18:03 UTC, TopAcademy2022 commented on messenger-client/Services/BlockInjections.cs
> +        public bool CheckForProhibitedSymbol(string verifiedText)
Replace method with LINQ.

2024-08-21 16:11 UTC, TopAcademy2022 requested changes

2024-08-21 16:11 UTC, TopAcademy2022 commented on messenger-client/Services/BlockInjections.cs
> +		public bool CheckProhibitedSymbols(string verifiedText)
Replace method with LINQ.

2024-08-21 16:50 UTC, xs887z approved these changes, later dismissed

2024-08-21 16:51 UTC, Andrey31ts submitted a review, later dismissed

2024-08-21 17:13 UTC, SugarSalt9 submitted a review, later dismissed

2024-08-21 17:22 UTC, TopAcademy2022 requested changes

2024-08-21 17:22 UTC, TopAcademy2022 commented on messenger-client/Services/BlockInjections.cs
> +			bool rezult = true;
Optimize this, remove variable.

2024-08-21 18:22 UTC, TopAcademy2022 approved these changes, later dismissed

2024-08-21 18:31 UTC, TopAcademy2022 approved these changes

2024-08-21 18:32 UTC, xs887z approved these changes

2024-08-23 15:37 UTC, SugarSalt9 approved these changes

2024-08-23 15:41 UTC, Mi-stik31 approved these changes

2024-08-23 15:46 UTC, merged